// RunesCodex — carga inicial de Hunts (teste)
// Fonte principal: Intibia. Dados podem estar marcados como desatualizados na fonte.
// Não altera schema/migrations. O importador pode usar estes registros para alimentar Hunt/HuntVocation/HuntCreature.

export const huntsSeed = [
  {
    name: "Venore Rotworm Cave",
    slug: "venore-rotworm-cave",
    location: "Venore",
    difficulty: "EASY",
    vocation: "EK",
    levelMin: 8,
    levelMax: 19,
    xpPerHour: 12000,
    profitPerHour: 1500,
    creatures: ["Rotworm"],
    sourceUrl: "https://intibia.com/pt/hunts/QrGc2/knight-venore-rotworm-cave",
  },
  {
    name: "Mistrock",
    slug: "mistrock",
    location: "Mistrock",
    difficulty: "EASY",
    vocation: "EK",
    levelMin: 8,
    levelMax: 19,
    xpPerHour: 80000,
    profitPerHour: -4000,
    creatures: ["Cyclops Smith", "Cyclops Drone", "Blood Crab"],
    sourceUrl: "https://intibia.com/pt/hunts/mgrGI/knight-mistrock-cyclops-stealth-ring",
  },
  {
    name: "Banuta",
    slug: "banuta",
    location: "Port Hope",
    difficulty: "EASY",
    vocation: "EK",
    levelMin: 20,
    levelMax: 34,
    xpPerHour: 75000,
    profitPerHour: 100000,
    creatures: [
      "Carniphila", "Terror Bird", "Merlkin", "Tarantula", "Kongra",
      "Sibang", "Tiger", "Centipede", "Cobra", "Wasp", "Poison Spider",
      "Spit Nettle", "Bug", "Spider", "Bat", "Snake", "Skunk",
      "Butterfly (Purple)", "Butterfly (Red)"
    ],
    sourceUrl: "https://intibia.com/pt/hunts/PbQOj/knight-banuta",
  },
  {
    name: "Venore Salamander Cave",
    slug: "venore-salamander-cave",
    location: "Venore",
    difficulty: "EASY",
    vocation: "EK",
    levelMin: 20,
    levelMax: 34,
    xpPerHour: 45000,
    profitPerHour: 60000,
    creatures: ["Marsh Stalker", "Swampling", "Emerald Damselfly", "Salamander"],
    sourceUrl: "https://intibia.com/pt/hunts/kzgsi/knight-venore-salamander-cave",
  },
  {
    name: "Alchemist Quarter",
    slug: "alchemist-quarter",
    location: "Yalahar",
    difficulty: "MEDIUM",
    vocation: "EK",
    levelMin: 20,
    levelMax: 34,
    xpPerHour: 120000,
    profitPerHour: 15000,
    creatures: ["Mutated Human", "Mutated Rat", "Mutated Bat"],
    sourceUrl: "https://intibia.com/pt/hunts/r7BmD/knight-alchemist-quarter-mutated-humans",
  },
  {
    name: "Corym Black Market",
    slug: "corym-black-market",
    location: "Venore",
    difficulty: "MEDIUM",
    vocation: "EK",
    levelMin: 35,
    levelMax: 49,
    xpPerHour: 110000,
    profitPerHour: 5000,
    creatures: ["Corym Skirmisher", "Corym Charlatan", "Corym Vanguard"],
    sourceUrl: "https://intibia.com/pt/hunts/Sv3az/knight-corym-black-market",
  },
  {
    name: "Nargor",
    slug: "nargor",
    location: "Nargor",
    difficulty: "MEDIUM",
    vocation: "EK",
    levelMin: 50,
    levelMax: 59,
    xpPerHour: 90000,
    profitPerHour: 25000,
    creatures: ["Pirate Buccaneer", "Pirate Corsair", "Smuggler", "Crab", "Pig"],
    sourceUrl: "https://intibia.com/pt/hunts/u3NCw/knight-nargor-pirates",
  },
  {
    name: "The Hive",
    slug: "the-hive-surface",
    location: "The Hive",
    difficulty: "MEDIUM",
    vocation: "EK",
    levelMin: 50,
    levelMax: 69,
    xpPerHour: 110000,
    profitPerHour: 0,
    creatures: ["Insectoid Worker", "Kollos", "Spitter"],
    sourceUrl: "https://intibia.com/pt/hunts/EYMqp/knight-the-hive-surface",
  },
  {
    name: "Lion's Rock",
    slug: "lions-rock",
    location: "Darashia",
    difficulty: "MEDIUM",
    vocation: "EK",
    levelMin: 60,
    levelMax: 79,
    xpPerHour: 430000,
    profitPerHour: 100000,
    creatures: ["Roaring Lion", "Noble Lion", "Ancient Scarab"],
    sourceUrl: "https://intibia.com/pt/hunts/Bb7ZW/knight-lions-rock",
  },
  {
    name: "Krailos Ruins",
    slug: "krailos-ruins",
    location: "Krailos",
    difficulty: "HARD",
    vocation: "EK",
    levelMin: 80,
    levelMax: 99,
    xpPerHour: 800000,
    profitPerHour: 100000,
    creatures: ["Nightmare Scion", "Lizard Legionnaire"],
    sourceUrl: "https://intibia.com/pt/hunts/vvL0n/knight-krailos-ruins-nightmare-scions",
  },
  {
    name: "Carlin Forbidden Temple",
    slug: "carlin-forbidden-temple-floor-1",
    location: "Carlin",
    difficulty: "HARD",
    vocation: "EK",
    levelMin: 80,
    levelMax: 99,
    xpPerHour: 700000,
    profitPerHour: 50000,
    creatures: ["Demon Skeleton", "Bonebeast", "Gargoyle"],
    sourceUrl: "https://intibia.com/pt/hunts/Mggaz/knight-carlin-forbidden-temple-floor-1-fire-bombs",
  },
  {
    name: "Yielothax Dimension",
    slug: "yielothax-dimension",
    location: "Yielothax Dimension",
    difficulty: "HARD",
    vocation: "EK",
    levelMin: 90,
    levelMax: 100,
    xpPerHour: 800000,
    profitPerHour: 150000,
    creatures: ["Yielothax"],
    sourceUrl: "https://intibia.com/pt/hunts/8bHDO/knight-yielothax-dimension",
  },
  {
    name: "Caverna Exanima",
    slug: "caverna-exanima",
    location: "Caverna Exanima",
    difficulty: "HARD",
    vocation: "EK",
    levelMin: 90,
    levelMax: 100,
    xpPerHour: 460000,
    profitPerHour: 300000,
    creatures: ["Putrid Mummy"],
    sourceUrl: "https://intibia.com/pt/hunts/WpxWi/knight-caverna-exanima-putrid-mummies",
  },
  {
    name: "Krailos Spider Lair",
    slug: "krailos-spider-lair",
    location: "Krailos",
    difficulty: "HARD",
    vocation: "EK",
    levelMin: 100,
    levelMax: 120,
    xpPerHour: 250000,
    profitPerHour: 20000,
    creatures: ["Giant Spider", "Brimstone Bug", "Wailing Widow"],
    sourceUrl: "https://intibia.com/pt/hunts/jHBKq/knight-krailos-spider-lair",
  },
  {
    name: "Drillworm Cave",
    slug: "drillworm-cave",
    location: "Kazordoon",
    difficulty: "HARD",
    vocation: "EK",
    levelMin: 100,
    levelMax: 120,
    xpPerHour: 250000,
    profitPerHour: 60000,
    creatures: ["Drillworm", "Giant Spider", "Earth Elemental", "Wyvern", "Stone Golem", "Carrion Worm"],
    sourceUrl: "https://intibia.com/hunts/QQlVE/knight-drillworm-cave",
  },
] as const;
